# define ANALOG_JOYSTICK_X_AXIS_PIN GP27
# define ANALOG_JOYSTICK_Y_AXIS_PIN GP26
# define POINTING_DEVICE_ROTATION_180
# define ANALOG_JOYSTICK_AUTO_AXIS

# define SPLIT_POINTING_ENABLE
# define POINTING_DEVICE_LEFT